---
- name: Add desktop repo keys w/ shell
  become: true
  shell:
    cmd: "{{ item }}"
    warn: false
  loop: "{{ repokeys }}"

- name: Add desktop repos
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: false
  loop: "{{ repos }}"

- name: Update repos and upgrade all packages
  become: true
  apt:
    update_cache: true
    autoremove: true
