---
- name: Install packages (apt)
  become: true
  package:
    name:
      - appimagelauncher #requires repo
      - audacity
      - baobab
      - chromium-browser
      - firejail
      - flatpak #included in 22.04
      - grub-customizer #requires repo for 22.04
      - gparted
      - kdeconnect
      - nohang
      - pandoc
      - pavucontrol
      - qbittorrent
      - qdirstat
      - ubuntu-restricted-extras
      - vlc
      - vokoscreen
      - xournalpp
    state: present
