---
- name: Install beeper
  shell: |
    curl -L https://download.beeper.com/linux/appImage/x64 --output beeper.AppImage
    chmod +x beeper.AppImage
    ail-cli integrate beeper.AppImage
  ignore_errors: true

- name: Install clickup
  shell: |
    curl -L https://desktop.clickup.com/linux --output clickup.AppImage
    chmod +x clickup.AppImage
    ail-cli integrate clickup.AppImage
  ignore_errors: false

- name: Install obsidian
  shell: |
    curl -L $(curl -s "https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest" | jq --raw-output '.assets[2].browser_download_url' | head -n1) --output obsidian.AppImage
    chmod +x obsidian.AppImage
    ail-cli integrate obsidian.AppImage
  ignore_errors: false

- name: Install plexamp
  shell: |
    curl https://plexamp.plex.tv/plexamp.plex.tv/desktop/Plexamp-4.2.1.AppImage --output plexamp.AppImage
    chmod +x plexamp.AppImage
    ail-cli integrate plexamp.AppImage
  ignore_errors: false
  
- name: Install FontBase
  shell: |
    curl https://releases.fontba.se/linux/FontBase-2.17.5.AppImage --output fontbase.AppImage
    chmod +x fontbase.AppImage
    ail-cli integrate fontbase.AppImage
  ignore_errors: false

