---
- name: Install mullvad
  become: true
  shell: |
    curl -L https://mullvad.net/download/app/deb/latest/ --output mullvad.deb
    apt-get -y install ./mullvad.deb
    rm mullvad.deb
  ignore_errors: true

- name: Install videodownloadhelper
  become: true
  shell: |
    curl https://github.com/mi-g/vdhcoapp/releases/download/v1.6.3-net.downloadhelper.coapp-1.6.3-1_amd64.deb --output vdh.deb
    apt-get -y install ./vdh.deb
    rm vdh.deb
  ignore_errors: true
