---
- name: Include variables
  include_vars:
    dir: vars

- include: add-repos.yml

- name: Update repos and upgrade all packages
  become: true
  apt:
    update_cache: true
    upgrade: yes
    autoremove: true

- include: install-packages.yml

- include: install-app-images.yml

- include: install-debs.yml

- name: Add flathub repository
  become: true
  shell:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install applications (flatpak)
  become: true
  flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ flatpaks }}"

- include: post-installation-cmds.yml
