---
- name: Include variables
  include_vars:
    dir: vars

- name: Add repo keys
  become: true
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ repokeys }}"

- name: Add repos
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: false
  loop: "{{ repos }}"

- name: Add ppas and apt update
  become: true
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ ppas }}"

- name: Add flatpak flathub repository
  become: true
  shell:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install desktop applications
  become: true
  package:
    name:
      - appimagelauncher
      - audacity
      - baobab
      - codium
      - chromium-browser
      - firejail
      - flatpak
      - grub-customizer
      - gparted
      - kdeconnect
      - nohang
      - pandoc
      - pavucontrol
      - qbittorrent
      - qdirstat
      - ubuntu-restricted-extras
      - vlc
      - vokoscreen
      - xournalpp
    state: present
    update_cache: false

- name: Install desktop applications (snap)
  become: true
  snap:
    name:
      - auto-cpufreq
      - mailspring

- name: Install desktop applications (flatpak)
  become: true
  flatpak:
    name:
      - com.github.debauchee.barrier
      - com.toggl.TogglDesktop
