---
- name: Include variables
  include_vars:
    dir: vars

- include: add-repos.yml

- include: install-packages.yml

- name: Install desktop applications (snap)
  become: true
  snap:
    name:
      - auto-cpufreq
      - mailspring

- name: Add flathub repository
  become: true
  shell:
    cmd: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install desktop applications (flatpak)
  become: true
  flatpak:
    name:
      - com.github.debauchee.barrier
      - com.toggl.TogglDesktop
