---
repos:
  - "deb [signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs vscodium main"
  - "ppa:appimagelauncher-team/stable"
  - "ppa:oibaf/test"
  - "ppa:danielrichter2007/grub-customizer"
  - "ppa:christian-boxdoerfer/fsearch-stable"
