---
- name: Install tailscale
  become: true
  shell:
    cmd: curl -fsSL https://tailscale.com/install.sh | sh

- name: Install rclone
  become: true
  shell:
    cmd: curl https://rclone.org/install.sh | sudo bash
