---
- name: Install packages (apt)
  become: true
  package:
    name:
      - ca-certificates
      - cifs-utils
      - docker-ce #requires repo
      - docker-ce-cli #requires repo
      - containerd.io #requires repo
      - docker-compose-plugin #requires repo
      - gnupg
      - htop
      - lsb-release
      - jq
      - software-properties-common
      - sshpass
      - syncthing #requires repo
      - tmux
      - vim
    state: present
