---
- name: Install tailscale
  become: true
  shell:
    cmd: curl -fsSL https://tailscale.com/install.sh | sh
    warn: false
  ignore_errors: true

- name: Install rclone
  become: true
  shell:
    cmd: curl https://rclone.org/install.sh | sudo bash
    warn: false
  ignore_errors: true

- name: Install netdata
  become: true
  shell:
    cmd: wget -O /tmp/netdata-kickstart.sh https://my-netdata.io/kickstart.sh && sh /tmp/netdata-kickstart.sh
    warn: false
  ignore_errors: true
