---
- name: Include variables
  include_vars:
    dir: vars

- name: Create ssh directory
  file:
    path: /home/travis/.ssh
    state: directory

- name: Generate ssh key
  openssh_keypair:
    path: /home/travis/.ssh/id_rsa

- name: Allow ufw openssh
  become: true
  ufw:
    rule: allow
    port: 22

- name: Enable ufw
  become: true
  ufw:
    state: enabled


- name: Install curl and gnupg
  become: true
  apt:
    pkg:
      - curl
      - gnupg

- include: add-repos.yml

- name: Update repos and upgrade all packages
  become: true
  apt:
    update_cache: true
    upgrade: yes
    cache_valid_time: 3600

- include: install-packages.yml

- include: install-w-shell.yml

- name: Setup oh my tmux!
  shell: |
    cd
    git clone https://github.com/gpakosz/.tmux.git
    ln -s -f .tmux/.tmux.conf
    cp .tmux/.tmux.conf.local .
