---
- name: Include variables
  include_vars:
    dir: vars

- name: Install curl and gnupg
  become: true
  apt:
    pkg:
      - curl
      - gnupg

- name: Add syncthing gpg key
  become: true
  shell:
    cmd: curl -o /usr/share/keyrings/syncthing-archive-keyring.gpg https://syncthing.net/release-key.gpg
    warn: false

- name: Add docker gpg key
  become: true
  shell:
    cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker.gpg
    warn: false

- name: Add vscodium gpg key
  become: true
  shell:
    cmd: wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg
    warn: false

- name: Add syncthing repo
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
    state: present
    update_cache: false

- name: Add docker repo
  become: true
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
    update_cache: false

- name: Add vscodium repo
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg] https://download.vscodium.com/debs vscodium main"
    state: present
    update_cache: false

- name: Update repos and upgrade all packages
  become: true
  apt:
    update_cache: true
    upgrade: yes
    autoremove: true
    cache_valid_time: 3600

- include: install-packages.yml

- name: Install tailscale
  become: true
  shell:
    cmd: curl -fsSL https://tailscale.com/install.sh | sh

- name: Install rclone
  become: true
  shell:
    cmd: curl https://rclone.org/install.sh | sudo bash

- name: Finish docker installation
  become: true
  shell: |
    newgrp docker
    sudo usermod -aG docker $USER
    sudo systemctl enable docker.service
    sudo systemctl enable containerd.service
    docker run -d -p 9001:9001 --name portainer_agent --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/docker/volumes:/var/lib/docker/volumes portainer/agent:latest
